name: {0}
description: {1}
group: {3}
license: {2}
upstream: https://gitee.com/src-oepkgs/{0}
branches:
- name: master
  type: protected
- name: openEuler-20.03-LTS-SP1
  type: protected
  create_from: master
- name: openEuler-20.03-LTS-SP2
  type: protected
  create_from: master
- name: openEuler-20.03-LTS-SP3
  type: protected
  create_from: master
- name: openEuler-22.03-LTS
  type: protected
  create_from: master
type: public